/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/cloud/model.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { IModelProps } from "@/data/interfaces";

export const Cloud = (props: IModelProps) => {
  const { nodes, materials } = useGLTF("/cloud/model.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Node.geometry}
        material={materials["lambert2SG.001"]}
      />
    </group>
  );
};

useGLTF.preload("/cloud/model.glb");
